
# QOF export as delivered by PRIMIS (except Asthma)
# NOTE: No resolved codes and no drug checks!!

$START_JOURNAL_SET; QOF1; CTV3; LTC; DIAGNOSES
$CODES; ASM1; 2; "H33..%","X1020"; "H44..%","H441..%","H440.%","X1025%","X1023","Xa01Z","XaKdk","XaJFG"; Asthma Candidates
$CODES; ASM2; 1; "21262"; Asthma Resolved
$CODES; QOFa; 1; "G573.%","G5730"; QOF
$CODES; QOFb; 1; "X78ef%","B32..%","B62y.%"; QOF
$CODES; QOFc; 1; "XE2uV%"; QOF
$CODES; QOFd; 1; "XaLHH%","XaLHG%","XaLHI%","XaLHJ%","XaLHK%"; QOF
#$CODES; QOFe; 1; "ZZZZZ"; QOF
$CODES; QOFf; 1; "H31..%","H32..%","H3...%"; QOF
$CODES; QOFg; 1; "X002w%","Xa1GB%","XE1Z6"; QOF
$CODES; QOFh; 1; "X00Sb","X00SO%"; QOF
$CODES; QOFi; 1; "X40J4%","X40J5%","X40J6"; QOF
#$CODES; QOFj; 1; "ZZZZZ"; QOF
$CODES; QOFk; 1; "G58..%"; QOF
$CODES; QOFl; 1; "XE0Ub","XE0Uc%","G24..%","G2...%","Xa0Cs","XSDSb","G202.","Xa3fQ"; QOF
$CODES; QOFm; 1; "E3...%","XaQZ4","XaQZ3","XaKYb","XaREt","XaREu","Eu81z"; QOF
$CODES; QOFn; 1; "X00S6%","X00SL","X00SM%","X00SJ%","XSGon","E11z.","E11z0","E11zz","XE1Ze","XE1ZZ","XaX54","XaX53"; QOF
$CODES; QOFo; 1; "1Z01.","XaQg1","8BA2.%","XaIse%","XaIpI","XaMhi","XaJv2%","8H6A.","8H7L.","XaAex","XaIlk","XaAg6","XaAT5","XaEJE%","XaAWN","XaAPW","XaRFG","XaRFF","9EB5.","ZV57C"; QOF
$CODES; QOFp; 1; "X00D1%","","ZV125","XE0VK%","XaX16"; QOF
$CODES; QOFq; 1; "X40IQ%","C061.%"; QOF
$END_JOURNAL_SET

